development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  timeout: 5000
  username: andrew
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  timeout: 5000
  username: andrew
  password:
